#         ____           _          __     ___      _               _
#  _   _ / ___|_ __ __ _| |_ ___  __\ \   / (_)_ __| |_ _   _  __ _(_)___
# | | | | |   | '__/ _` | __/ _ \/ __\ \ / /| | '__| __| | | |/ _` | / __|
# | |_| | |___| | | (_| | ||  __/\__ \\ V / | | |  | |_| |_| | (_| | \__ \
#  \__, |\____|_|  \__,_|\__\___||___/ \_/  |_|_|   \__|\__,_|\__,_|_|___/
#  |___/
#
# Discord: discord.ystoreplugins.com.br
# Site: ystoreplugins.com.br
#

# Modo de depuração para correção de problemas no plugin.
debug-mode: false

#      ___      _        _
#     /   \__ _| |_ __ _| |__   __ _ ___  ___
#    / /\ / _` | __/ _` | '_ \ / _` / __|/ _ \
#   / /_// (_| | || (_| | |_) | (_| \__ \  __/
#  /___,' \__,_|\__\__,_|_.__/ \__,_|___/\___|
#
# Configurações do banco de dados.

database:
  # Determina o tipo de banco de dados. Valores válidos: [SQLITE, MYSQL, HIKARI (recomendado)]
  storage-type: SQLITE

  # Dados para conexão ao banco de dados MYSQL.
  data:
    # Endereço de conexão do banco de dados. [EX: 127.0.0.1]
    host: localhost
    # Porta de conexão do banco de dados. [EX: 3306]
    port: 3306
    # Nome do banco de dados a ser conectado. [EX: minecraft]
    database: ''
    # Usuário de conexão. [EX: root]
    username: ''
    # Senha do usuário de conexão: [EX: 123]
    password: ''

#   __      _   _   _
#  / _\ ___| |_| |_(_)_ __   __ _ ___
#  \ \ / _ \ __| __| | '_ \ / _` / __|
#  _\ \  __/ |_| |_| | | | | (_| \__ \
#  \__/\___|\__|\__|_|_| |_|\__, |___/
#
# Sistemas principais.

# Delay para carregar os dados depois do login
# Necessário para usar em servidor de mina separado
# Recomendado: 20 ticks
login-delay: 20
# Delay para carregar os dados depois do servidor ligar
# Necessário para as crates em bloco
# Recomendado: 20 ticks
load-delay: 20

# Quebrar somente com o item dado pelo plugin?
break-only-plugin: true

# Diminuir o tempo de jogadores offline
minus-offline: false

# Prender por IP
arrest-ip: false

# Tag para o jogador preso
# é uma placeholder relacional
# Placeholder: %rel_yjail_arrested_tag%
tag: '&c[PRESO]'

# NBT de Itens que não serão guardados, mas sim deletados
nbt-item-delete:
  - 'yEventos-Item'
  - 'yGuerra-Item'

# Sistemas gerais
general:
  # Sistema de notificar jogadores presos/soltos (yDiscordHook)
  discordhook:
    enabled: true
    channel: ''
    # Placeholders disponíveis:
    # {player}
    # {staff}
    # {reason}
    # {time}
    embed-arrested: ''
    embed-released: ''
  # Sistema de notificar jogadores presos/soltos em webhook
  webhook:
    enabled: true
    # Placeholders disponíveis:
    # {player}
    # {staff}
    # {reason}
    # {time}
    embed-arrested: 'arrested'
    embed-released: 'released'